import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { EmptyState } from '../components/EmptyState'
import { Modal } from '../components/Modal'
import { Toast } from '../components/Toast'
import { useApp } from '../context/AppContext'

export function Players() {
  const { players, leaderboard, createPlayer, updatePlayer, deletePlayer, loading } = useApp(); const nav = useNavigate()
  const [modal, setModal] = useState<'add' | 'edit' | null>(null); const [editing, setEditing] = useState<{id:string;name:string} | null>(null); const [name, setName] = useState(''); const [error, setError] = useState(''); const [toast, setToast] = useState('')
  const stats = new Map(leaderboard.map(e => [e.player.id, e]))
  const submit = async () => { try { if (modal === 'add') { await createPlayer(name); setToast('Player added') } else if (editing) { await updatePlayer(editing.id, name); setToast('Player updated') }; setModal(null); setName(''); setError('') } catch (e:any) { setError(e.message) } }
  const openEdit = (p:{id:string;name:string}) => { setEditing(p); setName(p.name); setError(''); setModal('edit') }
  const remove = async (p:{id:string;name:string}) => { if (!window.confirm(`Remove ${p.name}? Their past games will stay in history.`)) return; try { await deletePlayer(p.id); setToast('Player removed') } catch (e:any) { setError(e.message) } }
  if (loading) return <div className="py-20 text-center text-gray-500">Loading players…</div>
  return <div className="space-y-5"><div className="flex items-end justify-between"><div><h1 className="text-2xl font-black">Players</h1><p className="mt-1 text-sm text-gray-500">Your Mahjong crew.</p></div><button onClick={() => { setName(''); setError(''); setModal('add') }} className="min-h-[48px] rounded-xl bg-brand px-4 text-sm font-bold shadow-glow active:scale-95">+ Add</button></div>{players.length ? <div className="space-y-2">{players.map(p => { const e = stats.get(p.id); return <div key={p.id} className="flex items-center gap-3 rounded-2xl border border-white/[.07] bg-panel p-4"><button onClick={() => nav(`/players/${p.id}`)} className="min-w-0 flex-1 text-left"><p className="truncate font-semibold">{p.name}</p><p className="mt-1 text-xs text-gray-500">{e?.winRate.toFixed(1) ?? '0.0'}% win rate · {e?.wins ?? 0}W · {e?.gamesPlayed ?? 0}G</p></button><button aria-label={`Edit ${p.name}`} onClick={() => openEdit(p)} className="grid h-10 w-10 place-items-center rounded-lg text-gray-500 hover:bg-white/5 hover:text-white">✎</button><button aria-label={`Delete ${p.name}`} onClick={() => remove(p)} className="grid h-10 w-10 place-items-center rounded-lg text-gray-500 hover:bg-red-900/30 hover:text-red-400">×</button></div> })}</div> : <EmptyState icon="♙" title="Add your first Mahjong player" description="You'll need four players to start a game." action={<button onClick={() => setModal('add')} className="rounded-xl bg-brand px-4 py-3 text-sm font-bold">+ Add Player</button>} />}
    <Modal open={modal !== null} onClose={() => setModal(null)} title={modal === 'edit' ? 'Edit player' : 'Add player'}><label className="text-xs font-bold uppercase tracking-wider text-gray-500" htmlFor="player-name">Player name</label><input id="player-name" autoFocus value={name} onChange={e => setName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') void submit() }} placeholder="e.g. John" maxLength={40} className="mt-2 h-14 w-full rounded-xl border border-white/10 bg-black px-4 text-white placeholder:text-gray-700" />{error && <p className="mt-2 text-sm text-red-400">{error}</p>}<div className="mt-5 flex gap-2"><button onClick={() => setModal(null)} className="min-h-[52px] flex-1 rounded-xl border border-white/10 font-semibold text-gray-400">Cancel</button><button onClick={() => void submit()} disabled={!name.trim()} className="min-h-[52px] flex-1 rounded-xl bg-brand font-bold disabled:opacity-40">{modal === 'edit' ? 'Save' : 'Add Player'}</button></div></Modal>{toast && <Toast message={toast} onDone={() => setToast('')} />}</div>
}
